
# Group 2 --- Project 3

### Importing libraries

In [2]:
import numpy as np
import matplotlib as pt
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from pandas import DataFrame

### Importing Dataset.

In [6]:
data = np.genfromtxt("mnist_data_selection.csv",delimiter=",", dtype="int")
# n is for last column of the dataset which is y
n = data.shape[1] -1

display(pd.DataFrame(data).head(10))

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9

### Splitting data

In [7]:
X = np.array(data[:,0:n])
y = np.array(data[:,n:n+1])

display(pd.DataFrame(X).head(10))
display(pd.DataFrame(y).head(10))

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

   0
0  9
1  3
2  4
3  3
4  5
5  8
6  2
7  1
8  1
9  9

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2)

training_data = np.hstack((X_train, y_train))
testing_data = np.hstack((X_test, y_test))

train = DataFrame(training_data)
test = DataFrame(testing_data)

train.to_csv("group2_tr.csv", index= False, header = None)
test.to_csv("group2_te.csv", index = False, header = None)